CREATE DATABASE IF NOT EXISTS board_db;

CREATE TABLE IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    filename VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE DATABASE `board_db2`;

USE `board_db2`;

DROP TABLE IF EXISTS `posts`;

CREATE TABLE `posts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NOT NULL,
  `filename` VARCHAR(255) DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `views` INT(11) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE posts ADD COLUMN author VARCHAR(255);

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL, -- 사용자 이름
  `userid` VARCHAR(255) NOT NULL UNIQUE, -- 로그인용 아이디
  `password` VARCHAR(255) NOT NULL, -- 암호화된 비밀번호
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 계정 생성 시간
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `posts`
ADD COLUMN `author_id` INT(11),
ADD CONSTRAINT `fk_author`
FOREIGN KEY (`author_id`) REFERENCES `users` (`id`)
ON DELETE SET NULL ON UPDATE CASCADE;

###############
CREATE TABLE IF NOT EXISTS `posts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NOT NULL,
  `filename` VARCHAR(255) DEFAULT NULL,
  `author` VARCHAR(255) NOT NULL, 
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `views` INT(11) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    userid VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE users CHANGE `PASSWORD` `password` VARCHAR(255) NOT NULL;
#SELECT COUNT(*) AS count FROM posts;
ALTER TABLE users ADD is_admin BOOLEAN DEFAULT FALSE; #관리자 컬럼추가
UPDATE users SET is_admin = TRUE WHERE userid = 'hong';